# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NA_Pros',
            fields=[
                ('summoner_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('summoner_name', models.CharField(max_length=16)),
                ('last_match_ID', models.IntegerField(null=True)),
            ],
        ),
    ]
